# Docker
# Build a Docker image 
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- none

steps:
  - task: PowerShell@2
    inputs:
      targetType: inline
      script: 'Write-Warning "##vso[task.setvariable variable=normalizedSystemKey]$(`"$(systemKey)`".Replace(''-'', ''''))"'


      